/**
 */

/*variable that states what is popular or not if below this limit it should not be counted as popular*/

var popLimit=1;

/* variable that states what counts as something beeing low in stock for the bartenders,
should probably be different for wine/beers/whiskeys
 */
var lowStockLimit= 50;

/*variable that states how many items of one beverage that must be in stock for a VIP-customer
 to be able to order beverage via interface
 */
var lowStockCustomer=10;

// just tells when something is out of stock :)
var notInStock=0;

/* these "data"variables are global to make it possible to see what happens but it would be better to use the API instead
 then updates would be "permanent" and not just temporary
  */

// here is every VIP-customers favorite beverages can be stored
var fav = getFavData();

/* here is all beverages that the flying dutchman has to offer, cointains information from inventory_get
and in addition its type, if its beer, cider, red wine or white wine
 */
var beerdata =getBeerData();

/*from the purchseData it is possible to calculate which beverages that are most sold
(would be better calculate how many times a beverage has been bought directly when a new purchase happens..)*/
var pop=getPurchaseData();

/* contans information about the users, for exemple their assets and username
(should not be declared this way but now its possible to see that
 * data was deleted without API) :) */
var VipData=getVipData();

// contains all usernames,passwords and if they are admin or not. Admin:1 means that the user is a Admin
// and Admin:0 means that the user is not and Admin
var users = getUsers();

/*contains comments that bartenders have added in the tab incidents*/
var historyData=getHistoryData();

function getHistoryData(){

    return [{"Username" : "ervtodd","timestamp":"2015-12-12", "comment":"A chair broke during the night"},
        {"Username" : "hirchr","timestamp":"2015-11-11" ,"comment": "Several glasses fell down, needs to order more"},
    ]

}

function getUsers() {
    return [
		 {"Firstname" : "Ervin","Lastname" : "Todd","Username" : "ervtodd","Password" : "ervtodd","Admin" : "1"},
        {"Firstname" : "Hiram","Lastname" : "Christopherson","Username" : "hirchr","Password" : "hirchr", "Admin" : "1"},
        {"Firstname" : "Jory","Lastname" : "Assies","Username" : "jorass","Password" : "jorass", "Admin" : "1"},
        {"Firstname" : "Saša","Lastname" : "Krüger","Username" : "saskru","Password" : "saskru", "Admin" : "1"},
        {"Firstname" : "Svetlana","Lastname" : "Torres","Username" : "svetor","Password" : "svetor", "Admin" : "1"},
        {"Firstname" : "Aamu","Lastname" : "Stankic","Username" : "aamsta","Password" : "aamsta", "Admin" : "0"},
        {"Firstname" : "Andrea","Lastname" : "Darzi","Username" : "anddar","Password" : "anddar", "Admin" : "0"},
        {"Firstname" : "Ângela","Lastname" : "Ková?","Username" : "ankov","Password" : "ankov", "Admin" : "0"},
        {"Firstname" : "Aquilina","Lastname" : "Lyndon","Username" : "aqulyn","Password" : "aqulyn", "Admin" : "0"},
        {"Firstname" : "Aubrey","Lastname" : "Blackwood","Username" : "aubbla","Password" : "aubbla", "Admin" : "0"},
        {"Firstname" : "Bento","Lastname" : "Faucher","Username" : "benfau","Password" : "benfau", "Admin" : "0"},
        {"Firstname" : "Branko","Lastname" : "Tamás","Username" : "bratam","Password" : "bratam", "Admin" : "0"},
        {"Firstname" : "Cezar","Lastname" : "Newman","Username" : "ceznew","Password" : "ceznew", "Admin" : "0"},
        {"Firstname" : "Danna","Lastname" : "Schermer","Username" : "dansch","Password" : "dansch", "Admin" : "0"},
        {"Firstname" : "Dido","Lastname" : "Waters","Username" : "didwat","Password" : "didwat", "Admin" : "0"},
        {"Firstname" : "Domen","Lastname" : "Olhouser","Username" : "domolh","Password" : "domolh", "Admin" : "0"},
        {"Firstname" : "Edric","Lastname" : "Augustin","Username" : "edraug","Password" : "edraug", "Admin" : "0"},
        {"Firstname" : "Einarr","Lastname" : "Yamauchi","Username" : "edraug","Password" : "einyam", "Admin" : "0"},
        {"Firstname" : "Elektra","Lastname" : "Pickle","Username" : "elepic","Password" : "elepic", "Admin" : "0"},
        {"Firstname" : "Eulàlia","Lastname" : "Coughlan","Username" : "eulcou","Password" : "eulcou", "Admin" : "0"},
        {"Firstname" : "Eustachius","Lastname" : "Gorski","Username" : "eusgor","Password" : "eusgor", "Admin" : "0"},
        {"Firstname" : "Felix","Lastname" : "Bartoš","Username" : "felbar","Password" : "felbar", "Admin" : "0"},
        {"Firstname" : "Felicia","Lastname" : "Franklin","Username" : "felfra","Password" : "felfra", "Admin" : "0"},
        {"Firstname" : "Ferdinánd","Lastname" : "Augustin","Username" : "fercrn","Password" : "fercrn", "Admin" : "0"},
        {"Firstname" : "Giacinta","Lastname" : "Mikkelsen","Username" : "giamik","Password" : "giamik", "Admin" : "0"},
        {"Firstname" : "Golnar","Lastname" : "Langley","Username" : "gollan","Password" : "gollan", "Admin" : "0"},
        {"Firstname" : "Hyram","Lastname" : "Lapointe","Username" : "hyrlap","Password" : "hyrlap", "Admin" : "0"},
        {"Firstname" : "Jacob","Lastname" : "Abbatelli","Username" : "jacabb","Password" : "jacabb", "Admin" : "0"},
        {"Firstname" : "Jancsi","Lastname" : "Heiman","Username" : "janhei","Password" : "janhei", "Admin" : "0"},
        {"Firstname" : "Jeanne","Lastname" : "Atses","Username" : "jeaats","Password" : "jeaats", "Admin" : "0"},
        {"Firstname" : "Jerry","Lastname" : "Shizuka","Username" : "jershi","Password" : "jershi", "Admin" : "0"},
        {"Firstname" : "Jove","Lastname" : "Sitz","Username" : "jovsit","Password" : "jovsit", "Admin" : "0"},
        {"Firstname" : "Karme","Lastname" : "Blythe","Username" : "karbly","Password" : "karbly", "Admin" : "0"},
        {"Firstname" : "Katrien","Lastname" : "Fabre","Username" : "katfab","Password" : "katfab", "Admin" : "0"},
        {"Firstname" : "Kaye","Lastname" : "Wang","Username" : "kaywan","Password" : "kaywan", "Admin" : "0"},
        {"Firstname" : "Kenan","Lastname" : "Olguin","Username" : "kenolg","Password" : "kenolg", "Admin" : "0"},
        {"Firstname" : "Krystyna","Lastname" : "Santiago","Username" : "krysan","Password" : "krysan", "Admin" : "0"},
        {"Firstname" : "Lara","Lastname" : "Schenck","Username" : "larsch","Password" : "larsch", "Admin" : "0"},
        {"Firstname" : "Lasse","Lastname" : "Nicholson","Username" : "lasnic","Password" : "lasnic", "Admin" : "0"},
        {"Firstname" : "Liam","Lastname" : "Traverso","Username" : "liatra","Password" : "liatra", "Admin" : "0"},
        {"Firstname" : "Livianus","Lastname" : "Zhao","Username" : "livzha","Password" : "livzha", "Admin" : "0"},
        {"Firstname" : "Maiken","Lastname" : "Honda","Username" : "maihon","Password" : "maihon", "Admin" : "0"},
        {"Firstname" : "Mariana","Lastname" : "Pugliese","Username" : "marpug","Password" : "marpug", "Admin" : "0"},
        {"Firstname" : "Marin","Lastname" : "Stieber","Username" : "marsti","Password" : "marsti", "Admin" : "0"},
        {"Firstname" : "Molle","Lastname" : "Babi?","Username" : "molbab","Password" : "molbab", "Admin" : "0"},
        {"Firstname" : "Muhammed","Lastname" : "Toft","Username" : "muhtof","Password" : "muhtof", "Admin" : "0"},
        {"Firstname" : "Nika","Lastname" : "Proulx","Username" : "nikpro","Password" : "nikpro", "Admin" : "0"},
        {"Firstname" : "Oliver","Lastname" : "Slusarski","Username" : "olislu","Password" : "olislu", "Admin" : "0"},
        {"Firstname" : "Oluwakanyinsola","Lastname" : "Braun","Username" : "olubra","Password" : "olubra", "Admin" : "0"},
        {"Firstname" : "Oluwatoyin","Lastname" : "Drake","Username" : "oludra","Password" : "oludra", "Admin" : "0"},
        {"Firstname" : "Orabela","Lastname" : "Panders","Username" : "orapan","Password" : "orapan", "Admin" : "0"},
        {"Firstname" : "Paula","Lastname" : "Aafjes","Username" : "pauaaf","Password" : "pauaaf", "Admin" : "0"},
        {"Firstname" : "Pompeius","Lastname" : "Graner","Username" : "pomgra","Password" : "pomgra", "Admin" : "0"},
        {"Firstname" : "Prabhakar","Lastname" : "Bartos","Username" : "prabar","Password" : "prabar", "Admin" : "0"},
        {"Firstname" : "Régulo","Lastname" : "Westerberg","Username" : "rewes","Password" : "rewes", "Admin" : "0"},
        {"Firstname" : "Schwanhild","Lastname" : "Joubert","Username" : "schjou","Password" : "schjou", "Admin" : "0"},
        {"Firstname" : "Sharma","Lastname" : "Pet?fi","Username" : "shapet","Password" : "shapet", "Admin" : "0"},
        {"Firstname" : "S?d?ka","Lastname" : "Van","Username" : "sivan","Password" : "sivan", "Admin" : "0"},
        {"Firstname" : "Stefan","Lastname" : "Bernard","Username" : "steber","Password" : "steber", "Admin" : "0"},
        {"Firstname" : "Sulis?aw","Lastname" : "Pender","Username" : "sulpen","Password" : "sulpen", "Admin" : "0"},
        {"Firstname" : "Sulayman","Lastname" : "Street","Username" : "sulstr","Password" : "sulstr", "Admin" : "0"},
        {"Firstname" : "Symeonu","Lastname" : "Zimmermann","Username" : "symzim","Password" : "symzim", "Admin" : "0"},
        {"Firstname" : "Teodora","Lastname" : "Jensen","Username" : "teojen","Password" : "teojen", "Admin" : "0"},
        {"Firstname" : "Tófa","Lastname" : "Heinrich","Username" : "tohei","Password" : "tohei", "Admin" : "0"},
        {"Firstname" : "Valeria","Lastname" : "Pagani","Username" : "valpag","Password" : "valpag", "Admin" : "0"},
        {"Firstname" : "Yevpraksiya","Lastname" : "Owens","Username" : "yevowe","Password" : "yevowe", "Admin" : "0"},
        {"Firstname" : "Zuleika","Lastname" : "Gorecki","Username" : "zulgor","Password" : "zulgor", "Admin" : "0"}
    ];
}



function getPurchaseData(){

    return [{"namn" : "Bedarö Bitter","namn2" : "","transaction_id" : "49619","user_id" : "17","beer_id" : "141001","timestamp" : "2015-12-04 13:06:33","price" : "28.20","first_name" : "Svetlana","last_name" : "Torres","username" : "svetor"},
        {"namn" : "Black Tower","namn2" : "Rivaner","transaction_id" : "49618","user_id" : "88","beer_id" : "604504","timestamp" : "2015-12-03 16:40:43","price" : "35.00","first_name" : "Testy","last_name" : "Test","username" : "testy"},
        {"namn" : "Black Tower","namn2" : "Rivaner","transaction_id" : "49617","user_id" : "88","beer_id" : "604504","timestamp" : "2015-12-03 16:38:07","price" : "35.00","first_name" : "Testy","last_name" : "Test","username" : "testy"},
        {"namn" : "Black Tower","namn2" : "Rivaner","transaction_id" : "49616","user_id" : "88","beer_id" : "604504","timestamp" : "2015-12-03 16:35:39","price" : "35.00","first_name" : "Testy","last_name" : "Test","username" : "testy"},
        {"namn" : "Black Tower","namn2" : "Rivaner","transaction_id" : "49615","user_id" : "88","beer_id" : "604504","timestamp" : "2015-12-03 16:33:18","price" : "35.00","first_name" : "Testy","last_name" : "Test","username" : "testy"},
        {"namn" : "Black Tower","namn2" : "Rivaner","transaction_id" : "49614","user_id" : "88","beer_id" : "604504","timestamp" : "2015-12-03 16:30:55","price" : "35.00","first_name" : "Testy","last_name" : "Test","username" : "testy"},
        {"namn" : "Campos Góticos","namn2" : "Tempranillo","transaction_id" : "49613","user_id" : "51","beer_id" : "209702","timestamp" : "2015-12-03 13:51:16","price" : "69.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Samuel Adams","namn2" : "Black Lager","transaction_id" : "49612","user_id" : "51","beer_id" : "153503","timestamp" : "2015-12-02 17:04:07","price" : "24.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Mahou Negra","namn2" : "","transaction_id" : "49611","user_id" : "51","beer_id" : "172303","timestamp" : "2015-12-02 17:04:02","price" : "24.20","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49607","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:34","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49608","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:34","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49609","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:34","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49610","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:34","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Leffe","namn2" : "Blonde","transaction_id" : "49579","user_id" : "51","beer_id" : "165903","timestamp" : "2015-12-02 13:00:33","price" : "10.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49580","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:33","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kloster","namn2" : "","transaction_id" : "49581","user_id" : "51","beer_id" : "8967303","timestamp" : "2015-12-02 13:00:33","price" : "19.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Leffe","namn2" : "Blonde","transaction_id" : "49582","user_id" : "51","beer_id" : "165903","timestamp" : "2015-12-02 13:00:33","price" : "10.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49583","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:33","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kloster","namn2" : "","transaction_id" : "49584","user_id" : "51","beer_id" : "8967303","timestamp" : "2015-12-02 13:00:33","price" : "19.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Leffe","namn2" : "Blonde","transaction_id" : "49585","user_id" : "51","beer_id" : "165903","timestamp" : "2015-12-02 13:00:33","price" : "10.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49586","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:33","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kloster","namn2" : "","transaction_id" : "49587","user_id" : "51","beer_id" : "8967303","timestamp" : "2015-12-02 13:00:33","price" : "19.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Leffe","namn2" : "Blonde","transaction_id" : "49588","user_id" : "51","beer_id" : "165903","timestamp" : "2015-12-02 13:00:33","price" : "10.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kung","namn2" : "","transaction_id" : "49589","user_id" : "51","beer_id" : "144612","timestamp" : "2015-12-02 13:00:33","price" : "99.00","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"},
        {"namn" : "Kloster","namn2" : "","transaction_id" : "49590","user_id" : "51","beer_id" : "8967303","timestamp" : "2015-12-02 13:00:33","price" : "19.90","first_name" : "Anders","last_name" : "Kovalchyck","username" : "ankov"}]
}



function getFavData() {
    return [
        {"Firstname" : "Aquilina","Lastname" : "Lyndon","Username" : "aqulyn", "fav_beer_id": ["157503","669702"]},
        {"Firstname" : "Aamu","Lastname" : "Stankic","Username" : "aamsta","fav_beer_id": []},
        {"Firstname" : "Andrea","Lastname" : "Darzi","Username" : "anddar","fav_beer_id": []},
        {"Firstname" : "Ângela","Lastname" : "Ková?","Username" : "ankov","fav_beer_id": []},
        {"Firstname" : "Aubrey","Lastname" : "Blackwood","Username" : "aubbla","fav_beer_id": []},
        {"Firstname" : "Bento","Lastname" : "Faucher","Username" : "benfau","fav_beer_id": []},
        {"Firstname" : "Branko","Lastname" : "Tamás","Username" : "bratam","fav_beer_id": []},
        {"Firstname" : "Cezar","Lastname" : "Newman","Username" : "ceznew","fav_beer_id": []},
        {"Firstname" : "Danna","Lastname" : "Schermer","Username" : "dansch","fav_beer_id": []},
        {"Firstname" : "Dido","Lastname" : "Waters","Username" : "didwat","fav_beer_id": []},
        {"Firstname" : "Domen","Lastname" : "Olhouser","Username" : "domolh","fav_beer_id": []},
        {"Firstname" : "Edric","Lastname" : "Augustin","Username" : "edraug","fav_beer_id": []},
        {"Firstname" : "Einarr","Lastname" : "Yamauchi","Username" : "edraug","fav_beer_id": []},
        {"Firstname" : "Elektra","Lastname" : "Pickle","Username" : "elepic","fav_beer_id": []},
        {"Firstname" : "Eulàlia","Lastname" : "Coughlan","Username" : "eulcou","fav_beer_id": []},
        {"Firstname" : "Eustachius","Lastname" : "Gorski","Username" : "eusgor","fav_beer_id": []},
        {"Firstname" : "Felix","Lastname" : "Bartoš","Username" : "felbar","fav_beer_id": []},
        {"Firstname" : "Felicia","Lastname" : "Franklin","Username" : "felfra","fav_beer_id": []},
        {"Firstname" : "Ferdinánd","Lastname" : "Augustin","Username" : "fercrn","fav_beer_id": []},
        {"Firstname" : "Giacinta","Lastname" : "Mikkelsen","Username" : "giamik","fav_beer_id": []},
        {"Firstname" : "Golnar","Lastname" : "Langley","Username" : "gollan","fav_beer_id": []},
        {"Firstname" : "Hyram","Lastname" : "Lapointe","Username" : "hyrlap","fav_beer_id": []},
        {"Firstname" : "Jacob","Lastname" : "Abbatelli","Username" : "jacabb","fav_beer_id": []},
        {"Firstname" : "Jancsi","Lastname" : "Heiman","Username" : "janhei","fav_beer_id": []},
        {"Firstname" : "Jeanne","Lastname" : "Atses","Username" : "jeaats","fav_beer_id": []},
        {"Firstname" : "Jerry","Lastname" : "Shizuka","Username" : "jershi","fav_beer_id": []},
        {"Firstname" : "Jove","Lastname" : "Sitz","Username" : "jovsit","fav_beer_id": []},
        {"Firstname" : "Karme","Lastname" : "Blythe","Username" : "karbly","fav_beer_id": []},
        {"Firstname" : "Katrien","Lastname" : "Fabre","Username" : "katfab","fav_beer_id": []},
        {"Firstname" : "Kaye","Lastname" : "Wang","Username" : "kaywan","fav_beer_id": []},
        {"Firstname" : "Kenan","Lastname" : "Olguin","Username" : "kenolg","fav_beer_id": []},
        {"Firstname" : "Krystyna","Lastname" : "Santiago","Username" : "krysan","fav_beer_id": []},
        {"Firstname" : "Lara","Lastname" : "Schenck","Username" : "larsch","fav_beer_id": []},
        {"Firstname" : "Lasse","Lastname" : "Nicholson","Username" : "lasnic","fav_beer_id": []},
        {"Firstname" : "Liam","Lastname" : "Traverso","Username" : "liatra","fav_beer_id": []},
        {"Firstname" : "Livianus","Lastname" : "Zhao","Username" : "livzha","fav_beer_id": []},
        {"Firstname" : "Maiken","Lastname" : "Honda","Username" : "maihon","fav_beer_id": []},
        {"Firstname" : "Mariana","Lastname" : "Pugliese","Username" : "marpug","fav_beer_id": []},
        {"Firstname" : "Marin","Lastname" : "Stieber","Username" : "marsti","fav_beer_id": []},
        {"Firstname" : "Molle","Lastname" : "Babi?","Username" : "molbab","fav_beer_id": []},
        {"Firstname" : "Muhammed","Lastname" : "Toft","Username" : "muhtof","fav_beer_id": []},
        {"Firstname" : "Nika","Lastname" : "Proulx","Username" : "nikpro","fav_beer_id": []},
        {"Firstname" : "Oliver","Lastname" : "Slusarski","Username" : "olislu","fav_beer_id": []},
        {"Firstname" : "Oluwakanyinsola","Lastname" : "Braun","Username" : "olubra","fav_beer_id": []},
        {"Firstname" : "Oluwatoyin","Lastname" : "Drake","Username" : "oludra","fav_beer_id": []},
        {"Firstname" : "Orabela","Lastname" : "Panders","Username" : "orapan","fav_beer_id": []},
        {"Firstname" : "Paula","Lastname" : "Aafjes","Username" : "pauaaf","fav_beer_id": []},
        {"Firstname" : "Pompeius","Lastname" : "Graner","Username" : "pomgra","fav_beer_id": []},
        {"Firstname" : "Prabhakar","Lastname" : "Bartos","Username" : "prabar","fav_beer_id": []},
        {"Firstname" : "Régulo","Lastname" : "Westerberg","Username" : "rewes","fav_beer_id": []},
        {"Firstname" : "Schwanhild","Lastname" : "Joubert","Username" : "schjou","fav_beer_id": []},
        {"Firstname" : "Sharma","Lastname" : "Pet?fi","Username" : "shapet","fav_beer_id": []},
        {"Firstname" : "S?d?ka","Lastname" : "Van","Username" : "sivan","fav_beer_id": []},
        {"Firstname" : "Stefan","Lastname" : "Bernard","Username" : "steber","fav_beer_id": []},
        {"Firstname" : "Sulis?aw","Lastname" : "Pender","Username" : "sulpen","fav_beer_id": []},
        {"Firstname" : "Sulayman","Lastname" : "Street","Username" : "sulstr","fav_beer_id": []},
        {"Firstname" : "Symeonu","Lastname" : "Zimmermann","Username" : "symzim","fav_beer_id": []},
        {"Firstname" : "Teodora","Lastname" : "Jensen","Username" : "teojen","fav_beer_id": []},
        {"Firstname" : "Tófa","Lastname" : "Heinrich","Username" : "tohei","fav_beer_id": []},
        {"Firstname" : "Valeria","Lastname" : "Pagani","Username" : "valpag","fav_beer_id": []},
        {"Firstname" : "Yevpraksiya","Lastname" : "Owens","Username" : "yevowe","fav_beer_id": []},
        {"Firstname" : "Zuleika","Lastname" : "Gorecki","Username" : "zulgor","fav_beer_id": []}

    ]
}



function getVipData() {
    return [
        {"username" : "anddar","first_name" : "Andrea","last_name" : "Darzi","assets" : "-357460"},
        {"username" : "aamsta","first_name" : "Aamu","last_name" : "Stankic","assets" : "-5120"},
        {"username" : "maihon","first_name" : "Maiken","last_name" : "Honda","assets" : "-3415"},
        {"username" : "ankov","first_name" : "Anders","last_name" : "Kovalchyck","assets" : "-3210"},
        {"username" : "jovsit","first_name" : "Zlatan","last_name" : "Ibrahimovic","assets" : "-1637"},
        {"username" : "liatra","first_name" : "Liam","last_name" : "Traverso","assets" : "-1055"},
        {"username" : "dansch","first_name" : "Danna","last_name" : "Schermer","assets" : "-985"},
        {"username" : "pauaaf","first_name" : "Paula","last_name" : "Aafjes","assets" : "-720"},
        {"username" : "undefined","first_name" : "Hej","last_name" : "Då","assets" : "-440"},
        {"username" : "ervtod","first_name" : "Ervin","last_name" : "Todd","assets" : "-345"},
        {"username" : "eulcou","first_name" : "Eul�lia","last_name" : "Coughlan","assets" : "-270"},
        {"username" : "livzha","first_name" : "Livianus","last_name" : "Zhao","assets" : "-260"},
        {"username" : "lasnic","first_name" : "Lasse","last_name" : "Nicholson","assets" : "-250"},
        {"username" : "testy","first_name" : "Testy","last_name" : "Test","assets" : "-200"},
        {"username" : "kenolg","first_name" : "Kenan","last_name" : "Olguin","assets" : "-187"},
        {"username" : "elepic","first_name" : "Elektra","last_name" : "Pickle","assets" : "-185"},
        {"username" : "gollan","first_name" : "Golnar","last_name" : "Langley","assets" : "-150"},
        {"username" : "felbar","first_name" : "Felix","last_name" : "Barto�","assets" : "-125"},
        {"username" : "einyam","first_name" : "Einarr","last_name" : "Yamauchi","assets" : "-115"},
        {"username" : "hyrlap","first_name" : "Hyram","last_name" : "Lapointe","assets" : "-105"},
        {"username" : "tohei","first_name" : "T�fa","last_name" : "Heinrich","assets" : "-85"},
        {"username" : "sulpen","first_name" : "Sulis?aw","last_name" : "Pender","assets" : "-60"},
        {"username" : "hirchr","first_name" : "Hiram","last_name" : "Christopherson","assets" : "-55"},
        {"username" : "giamik","first_name" : "Giacinta","last_name" : "Mikkelsen","assets" : "-50"},
        {"username" : "sulstr","first_name" : "Sulayman","last_name" : "Street","assets" : "-40"},
        {"username" : "karbly","first_name" : "Karme","last_name" : "Blythe","assets" : "-40"},
        {"username" : "valpag","first_name" : "Valeria","last_name" : "Pagani","assets" : "-35"},
        {"username" : "bratam","first_name" : "Branko","last_name" : "Tam�s","assets" : "-30"},
        {"username" : "shapet","first_name" : "Sharma","last_name" : "Pet?fi","assets" : "-30"},
        {"username" : "marsti","first_name" : "Marin","last_name" : "Stieber","assets" : "-30"},
        {"username" : "symzim","first_name" : "Symeonu","last_name" : "Zimmermann","assets" : "-25"},
        {"username" : "edraug","first_name" : "Edric","last_name" : "Augustin","assets" : "-25"},
        {"username" : "nikpro","first_name" : "Nika","last_name" : "Proulx","assets" : "-20"},
        {"username" : "fercrn","first_name" : "Ferdin�nd","last_name" : "Crncevic","assets" : "-15"},
        {"username" : "steber","first_name" : "Stefan","last_name" : "Bernard","assets" : "-15"},
        {"username" : "didwat","first_name" : "Dido","last_name" : "Waters","assets" : "-5"},
        {"username" : "olubra","first_name" : "Oluwakanyinsola","last_name" : "Braun","assets" : "-5"},
        {"username" : "jeaats","first_name" : "Jeanne","last_name" : "Atses","assets" : "0"},
        {"username" : "pomgra","first_name" : "Pompeius","last_name" : "Graner","assets" : "0"},
        {"username" : "krysan","first_name" : "Krystyna","last_name" : "Santiago","assets" : "0"},
        {"username" : "yevowe","first_name" : "Yevpraksiya","last_name" : "Owens","assets" : "0"},
        {"username" : "benfau","first_name" : "Bento","last_name" : "Faucher","assets" : "0"},
        {"username" : "orapan","first_name" : "Orabela","last_name" : "Panders","assets" : "0"},
        {"username" : "teojen","first_name" : "Teodora","last_name" : "Jensen","assets" : "0"},
        {"username" : "oludra","first_name" : "Oluwatoyin","last_name" : "Drake","assets" : "0"},
        {"username" : "ceznew","first_name" : "Cezar","last_name" : "Newman","assets" : "0"},
        {"username" : "jershi","first_name" : "Jerry","last_name" : "Shizuka","assets" : "0"},
        {"username" : "molbab","first_name" : "Molle","last_name" : "Babi?","assets" : "5"},
        {"username" : "larsch","first_name" : "Lara","last_name" : "Schenck","assets" : "5"},
        {"username" : "schjou","first_name" : "Schwanhild","last_name" : "Joubert","assets" : "10"},
        {"username" : "felfra","first_name" : "Felicia","last_name" : "Franklin","assets" : "10"},
        {"username" : "janhei","first_name" : "Jancsi","last_name" : "Heiman","assets" : "15"},
        {"username" : "foobar","first_name" : "Foo","last_name" : "Bar","assets" : "15"},
        {"username" : "domolh","first_name" : "Domen","last_name" : "Olhouser","assets" : "15"},
        {"username" : "marpug","first_name" : "Mariana","last_name" : "Pugliese","assets" : "20"},
        {"username" : "kaywan","first_name" : "Kaye","last_name" : "Wang","assets" : "25"},
        {"username" : "jacabb","first_name" : "Jacob","last_name" : "Abbatelli","assets" : "25"},
        {"username" : "rewes","first_name" : "R�gulo","last_name" : "Westerberg","assets" : "25"},
        {"username" : "muhtof","first_name" : "Muhammed","last_name" : "Toft","assets" : "25"},
        {"username" : "eusgor","first_name" : "Eustachius","last_name" : "Gorski","assets" : "45"},
        {"username" : "katfab","first_name" : "Katrien","last_name" : "Fabre","assets" : "50"},
        {"username" : "olislu","first_name" : "Oliver","last_name" : "Slusarski","assets" : "65"},
        {"username" : "saskru","first_name" : "Sa�a","last_name" : "Kr�ger","assets" : "110"},
        {"username" : "zulgor","first_name" : "Zuleika","last_name" : "Gorecki","assets" : "120"},
        {"username" : "aubbla","first_name" : "Aubrey","last_name" : "Blackwood","assets" : "150"},
        {"username" : "prabar","first_name" : "Prabhakar","last_name" : "Bartos","assets" : "170"},
        {"username" : "sivan","first_name" : "S?d?ka","last_name" : "Van","assets" : "235"},
        {"username" : "pierre","first_name" : "Pierre","last_name" : "Flener","assets" : "1000"},
        {"username" : "aqulyn","first_name" : "Aquilina","last_name" : "Lyndon","assets" : "1248"},
        {"username" : "svetor","first_name" : "Svetlana","last_name" : "Torres","assets" : "8036"},
        {"username" : "jorass","first_name" : "Jory","last_name" : "Assies","assets" : "8995"}
    ]


}


function getBeerData() {
    return [

        {"namn" : "Anchor Steam Beer","namn2" : "","sbl_price" : "23.90","pub_price" : "25","beer_id" : "157503","count" : "10","price" : "20.60", "type":"öl"},
        {"namn" : "Beck's","namn2" : "","sbl_price" : "14.90","pub_price" : "20","beer_id" : "154903","count" : "3","price" : "14.10", "type":"öl"},
        {"namn" : "Bedarö Bitter","namn2" : "","sbl_price" : "28.60","pub_price" : "30","beer_id" : "141001","count" : "1","price" : "28.20", "type":"öl"},
        {"namn" : "BEO","namn2" : "Apple Green Tea","sbl_price" : "12.90","pub_price" : "15","beer_id" : "197702","count" : "3","price" : "12.90", "type":"alcohol-free"},
        {"namn" : "BEO","namn2" : "Blood Orange Hibiscus","sbl_price" : "12.90","pub_price" : "15","beer_id" : "197302","count" : "2","price" : "12.90", "type":"alcohol-free"},
        {"namn" : "Bitburger","namn2" : "Premium","sbl_price" : "12.60","pub_price" : "15","beer_id" : "156503","count" : "6","price" : "11.90", "type":"öl"},
        {"namn" : "Black Tower","namn2" : "Rivaner","sbl_price" : "29.00","pub_price" : "35","beer_id" : "604504","count" : "47","price" : "29.00", "type":"vitt_vin"},
        {"namn" : "Blue Nun","namn2" : "","sbl_price" : "38.00","pub_price" : "40","beer_id" : "693502","count" : "05","price" : "36.00", "type":"vitt_vin"},
        {"namn" : "Bombardier","namn2" : "","sbl_price" : "20.90","pub_price" : "25","beer_id" : "152901","count" : "8","price" : "19.90", "type":"öl"},{"namn" : "Brewdog","namn2" : "5 A.M. Saint","sbl_price" : "20.10","pub_price" : "25","beer_id" : "150103","count" : "0","price" : "20.10", "type":"öl"},
        {"namn" : "BrewDog Dead Pony Club","namn2" : "","sbl_price" : "18.40","pub_price" : "20","beer_id" : "1191303","count" : "4","price" : "18.10", "type":"öl"},
        {"namn" : "Brewdog Hardcore IPA","namn2" : "","sbl_price" : "28.90","pub_price" : "30","beer_id" : "159103","count" : "70","price" : "36.00", "type":"öl"},
        {"namn" : "Brewdog Punk IPA","namn2" : "","sbl_price" : "21.40","pub_price" : "25","beer_id" : "151503","count" : "12","price" : "19.90", "type":"öl"},
        {"namn" : "BrewDog Rip Tide","namn2" : "","sbl_price" : "27.90","pub_price" : "30","beer_id" : "162003","count" : "14","price" : "26.90", "type":"öl"},
        {"namn" : "BrewDog Trashy Blonde","namn2" : "","sbl_price" : "19.90","pub_price" : "25","beer_id" : "1158103","count" : "3","price" : "18.90", "type":"öl"},
        {"namn" : "Briccotondo","namn2" : "Barbera","sbl_price" : "79.00","pub_price" : "85","beer_id" : "277301","count" : "11","price" : "79.00", "type":"rött_vin"},
        {"namn" : "Brooklyn","namn2" : "East India Pale Ale","sbl_price" : "23.90","pub_price" : "25","beer_id" : "168803","count" : "21","price" : "22.90", "type":"öl"},
        {"namn" : "Brooklyn Lager","namn2" : "","sbl_price" : "17.90","pub_price" : "20","beer_id" : "154803","count" : "4","price" : "16.90", "type":"öl"},
        {"namn" : "Cameleon","namn2" : "Selection Malbec","sbl_price" : "43.00","pub_price" : "45","beer_id" : "658102","count" : "80","price" : "43.00", "type":"rött_vin"},
        {"namn" : "Campos Góticos","namn2" : "Tempranillo","sbl_price" : "49.00","pub_price" : "55","beer_id" : "209702","count" : "202","price" : "49.00", "type":"rött_vin"},
        {"namn" : "Casillero del Diablo","namn2" : "Chardonnay","sbl_price" : "29.00","pub_price" : "35","beer_id" : "207504","count" : "203","price" : "30.00", "type":"vitt_vin"},
        {"namn" : "Ch Malavieille Alliance","namn2" : "","sbl_price" : "119.00","pub_price" : "125","beer_id" : "266201","count" : "194","price" : "119.00", "type":"rött_vin"},
        {"namn" : "Château Pech-Latt","namn2" : "","sbl_price" : "99.00","pub_price" : "105","beer_id" : "223301","count" : "201","price" : "99.00", "type":"rött_vin"},
        {"namn" : "Chilcas","namn2" : "Sauvignon Blanc","sbl_price" : "46.00","pub_price" : "50","beer_id" : "669702","count" : "200","price" : "45.00", "type":"vitt_vin"},
        {"namn" : "Chill Out Mountains","namn2" : "Malbec","sbl_price" : "69.00","pub_price" : "75","beer_id" : "614601","count" : "177","price" : "69.00", "type":"rött_vin"},
        {"namn" : "Chimay blå","namn2" : "","sbl_price" : "29.90","pub_price" : "35","beer_id" : "165103","count" : "192","price" : "28.90", "type":"öl"},
        {"namn" : "Cidraie Pear","namn2" : "","sbl_price" : "20.00","pub_price" : "25","beer_id" : "180202","count" : "198","price" : "20.00", "type":"cider"},
        {"namn" : "Citra Pale Ale","namn2" : "","sbl_price" : "20.90","pub_price" : "25","beer_id" : "155103","count" : "193","price" : "20.90", "type":"öl"},
        {"namn" : "Coopers Best","namn2" : "Extra Stout","sbl_price" : "19.90","pub_price" : "25","beer_id" : "1127103","count" : "197","price" : "19.90", "type":"öl"},
        {"namn" : "Dr L","namn2" : "Riesling","sbl_price" : "81.00","pub_price" : "85","beer_id" : "721801","count" : "183","price" : "81.00", "type":"vitt_vin"},
        {"namn" : "Duvel","namn2" : "","sbl_price" : "25.50","pub_price" : "30","beer_id" : "165403","count" : "171","price" : "24.90", "type":"öl"},
        {"namn" : "Ecologica","namn2" : "Shiraz Malbec","sbl_price" : "69.00","pub_price" : "75","beer_id" : "651201","count" : "194","price" : "69.00", "type":"rött_vin"},
        {"namn" : "Einbecker Brauherren Alkoholfrei","namn2" : "","sbl_price" : "9.90","pub_price" : "15","beer_id" : "191402","count" : "193","price" : "9.90", "type":"alcohol-free"},
        {"namn" : "El Cortejo","namn2" : "Sauvignon Blanc","sbl_price" : "34.00","pub_price" : "40","beer_id" : "601202","count" : "184","price" : "33.00", "type":"vitt_vin"},
        {"namn" : "El Coto","namn2" : "Blanco","sbl_price" : "37.00","pub_price" : "40","beer_id" : "278002","count" : "189","price" : "37.00", "type":"vitt_vin"},
        {"namn" : "Electric Nurse","namn2" : "Imperial Stout","sbl_price" : "34.90","pub_price" : "40","beer_id" : "8953903","count" : "196","price" : "34.90", "type":"öl"},
        {"namn" : "Erdinger","namn2" : "Weissbier Hefe","sbl_price" : "21.90","pub_price" : "25","beer_id" : "1120801","count" : "192","price" : "21.90", "type":"öl"},
        {"namn" : "Fentimans","namn2" : "Ginger Beer","sbl_price" : "22.50","pub_price" : "25","beer_id" : "196303","count" : "197","price" : "22.50", "type":"alcohol-free"},
        {"namn" : "Flying Dog","namn2" : "Dogtoberfest Märzen","sbl_price" : "25.90","pub_price" : "30","beer_id" : "1163903","count" : "209","price" : "25.90", "type":"öl"},
        {"namn" : "Flying Dog","namn2" : "Gonzo Imperial Porter","sbl_price" : "29.90","pub_price" : "35","beer_id" : "168303","count" : "204","price" : "29.90", "type":"öl"},
        {"namn" : "Franziskaner","namn2" : "Hefe-Weissbier","sbl_price" : "21.90","pub_price" : "25","beer_id" : "168701","count" : "208","price" : "20.50", "type":"öl"},
        {"namn" : "Freedom IPA","namn2" : "","sbl_price" : "27.40","pub_price" : "30","beer_id" : "8968701","count" : "209","price" : "27.00", "type":"öl"},
        {"namn" : "Fuller's ESB","namn2" : "","sbl_price" : "25.90","pub_price" : "30","beer_id" : "1140501","count" : "193","price" : "25.40", "type":"öl"},
        {"namn" : "Gambrinus","namn2" : "","sbl_price" : "16.50","pub_price" : "20","beer_id" : "1148901","count" : "200","price" : "15.90", "type":"öl"},
        {"namn" : "Guinness","namn2" : "Extra Stout","sbl_price" : "17.90","pub_price" : "20","beer_id" : "156103","count" : "199","price" : "16.90", "type":"öl"},
        {"namn" : "Hell","namn2" : "","sbl_price" : "25.90","pub_price" : "30","beer_id" : "1146001","count" : "209","price" : "23.80", "type":"öl"},
        {"namn" : "Hoegaarden","namn2" : "Wit-Blanche","sbl_price" : "17.40","pub_price" : "20","beer_id" : "156303","count" : "54","price" : "16.10", "type":"öl"},
        {"namn" : "Hofbräu München Oktoberfest","namn2" : "","sbl_price" : "19.90","pub_price" : "25","beer_id" : "1129801","count" : "200","price" : "19.90", "type":"öl"},
        {"namn" : "Hubert Beck","namn2" : "Réserve du Chevalier Pinot Gris","sbl_price" : "49.00","pub_price" : "55","beer_id" : "1210502","count" : "197","price" : "49.00", "type":"vitt_vin"},
        {"namn" : "il Conte","namn2" : "Montepulciano d'Abruzzo","sbl_price" : "38.00","pub_price" : "40","beer_id" : "232202","count" : "205","price" : "36.00" , "type":"rött_vin"},
        {"namn" : "il Nostro","namn2" : "Grecanico","sbl_price" : "57.00","pub_price" : "60","beer_id" : "2280301","count" : "202","price" : "57.00", "type":"vitt_vin"},
        {"namn" : "Innis & Gunn","namn2" : "Oak Aged Beer","sbl_price" : "19.90","pub_price" : "25","beer_id" : "1144703","count" : "206","price" : "19.90", "type":"öl"},
        {"namn" : "Innis & Gunn","namn2" : "Rum Finish Oak Aged Beer","sbl_price" : "19.90","pub_price" : "25","beer_id" : "1159803","count" : "200","price" : "19.90", "type":"öl"},
        {"namn" : "Jever Pilsener","namn2" : "","sbl_price" : "12.90","pub_price" : "15","beer_id" : "150603","count" : "207","price" : "12.90", "type":"öl"},
        {"namn" : "Jever Pilsener","namn2" : "","sbl_price" : "16.90","pub_price" : "20","beer_id" : "150601","count" : "197","price" : "15.90", "type":"öl"},
        {"namn" : "Karlovacko","namn2" : "","sbl_price" : "17.80","pub_price" : "20","beer_id" : "151001","count" : "198","price" : "16.90", "type":"öl"},
        {"namn" : "Kasteel Triple","namn2" : "","sbl_price" : "40.80","pub_price" : "45","beer_id" : "8910403","count" : "196","price" : "27.50", "type":"öl"},
        {"namn" : "Königsmosel","namn2" : "Riesling","sbl_price" : "39.00","pub_price" : "45","beer_id" : "746902","count" : "200","price" : "39.00", "type":"vitt_vin"},
        {"namn" : "King Goblin","namn2" : "","sbl_price" : "26.90","pub_price" : "30","beer_id" : "150401","count" : "198","price" : "25.90", "type":"öl"},
        {"namn" : "Kiviks Astrakan Fläderblom","namn2" : "Äppelcider Halvtorr","sbl_price" : "19.90","pub_price" : "25","beer_id" : "187702","count" : "199","price" : "19.90", "type":"cider"},
        {"namn" : "Kiviks Astrakan","namn2" : "Torr Cider","sbl_price" : "19.90","pub_price" : "25","beer_id" : "181803","count" : "199","price" : "18.90", "type":"cider"},
        {"namn" : "Kiviks Williams","namn2" : "Päroncider Halvtorr","sbl_price" : "19.90","pub_price" : "25","beer_id" : "183203","count" : "199","price" : "18.90", "type":"cider"},
        {"namn" : "Kloster","namn2" : "","sbl_price" : "32.30","pub_price" : "35","beer_id" : "8967303","count" : "192","price" : "32.30", "type":"öl"},
        {"namn" : "Kung","namn2" : "","sbl_price" : "10.40","pub_price" : "15","beer_id" : "144612","count" : "178","price" : "10.60", "type":"öl"},
        {"namn" : "Kwak","namn2" : "","sbl_price" : "23.90","pub_price" : "25","beer_id" : "166403","count" : "200","price" : "23.90", "type":"öl"},
        {"namn" : "Lapin Kulta","namn2" : "","sbl_price" : "13.40","pub_price" : "15","beer_id" : "159412","count" : "11","price" : "13.10", "type":"öl"},
        {"namn" : "Leffe","namn2" : "Blonde","sbl_price" : "19.90","pub_price" : "25","beer_id" : "165903","count" : "188","price" : "18.90", "type":"öl"},
        {"namn" : "Leffe","namn2" : "Brune","sbl_price" : "19.90","pub_price" : "25","beer_id" : "133603","count" : "202","price" : "19.60", "type":"öl"},
        {"namn" : "Leitz Eins Zwei Dry","namn2" : "Riesling","sbl_price" : "99.00","pub_price" : "105","beer_id" : "582201","count" : "200","price" : "99.00", "type":"vitt_vin"},
        {"namn" : "Lindemans Bin 65","namn2" : "Chardonnay","sbl_price" : "45.00","pub_price" : "50","beer_id" : "210602","count" : "191","price" : "43.00", "type":"vitt_vin"},
        {"namn" : "Mahou Negra","namn2" : "","sbl_price" : "14.90","pub_price" : "20","beer_id" : "172303","count" : "198","price" : "15.20", "type":"öl"},
        {"namn" : "Mariestads","namn2" : "Alkoholfri","sbl_price" : "10.90","pub_price" : "15","beer_id" : "195202","count" : "199","price" : "10.90", "type":"alcohol-free"},
        {"namn" : "Mariestads Export","namn2" : "","sbl_price" : "15.90","pub_price" : "20","beer_id" : "120301","count" : "204","price" : "15.40", "type":"öl"},
        {"namn" : "Mariestads Export","namn2" : "","sbl_price" : "13.90","pub_price" : "15","beer_id" : "120003","count" : "170","price" : "13.90", "type":"öl"},
        {"namn" : "Mariestads Old Ox","namn2" : "","sbl_price" : "17.50","pub_price" : "20","beer_id" : "137901","count" : "201","price" : "17.50", "type":"öl"},
        {"namn" : "Mikkeller","namn2" : "American Dream","sbl_price" : "24.20","pub_price" : "30","beer_id" : "8966103","count" : "200","price" : "28.90", "type":"öl"},
        {"namn" : "Mikkeller","namn2" : "Drink'in The Sun","sbl_price" : "16.90","pub_price" : "20","beer_id" : "1199403","count" : "202","price" : "16.90", "type":"alcohol-free"},
        {"namn" : "Miller","namn2" : "Genuine Draft","sbl_price" : "14.90","pub_price" : "20","beer_id" : "157903","count" : "200","price" : "14.90", "type":"öl"},
        {"namn" : "Modus Hoperandi","namn2" : "India Pale Ale","sbl_price" : "22.90","pub_price" : "25","beer_id" : "153915","count" : "196","price" : "22.90", "type":"öl"},
        {"namn" : "Mountain Livin'","namn2" : "Pale Ale","sbl_price" : "24.90","pub_price" : "30","beer_id" : "8916315","count" : "168","price" : "25.20", "type":"öl"},
        {"namn" : "Nanny State","namn2" : "","sbl_price" : "12.90","pub_price" : "15","beer_id" : "194703","count" : "199","price" : "12.40", "type":"alcohol-free"},
        {"namn" : "Napa Smith","namn2" : "West Coast IPA","sbl_price" : "23.90","pub_price" : "25","beer_id" : "168103","count" : "199","price" : "23.90", "type":"öl"},
        {"namn" : "Newcastle Brown Ale","namn2" : "","sbl_price" : "15.70","pub_price" : "20","beer_id" : "153803","count" : "193","price" : "15.20", "type":"öl"},
        {"namn" : "Nils Oscar","namn2" : "India Ale","sbl_price" : "19.20","pub_price" : "25","beer_id" : "146403","count" : "200","price" : "18.90", "type":"öl"},
        {"namn" : "Old Speckled Hen","namn2" : "","sbl_price" : "22.80","pub_price" : "25","beer_id" : "135601","count" : "199","price" : "22.80", "type":"öl"},
        {"namn" : "Old Speckled Hen","namn2" : "","sbl_price" : "14.90","pub_price" : "20","beer_id" : "135603","count" : "199","price" : "15.90", "type":"öl"},
        {"namn" : "Omnipollo Leon","namn2" : "","sbl_price" : "49.90","pub_price" : "55","beer_id" : "169301","count" : "200","price" : "49.90", "type":"öl"},
        {"namn" : "Omnipollo","namn2" : "Nebuchadnezzar","sbl_price" : "29.90","pub_price" : "35","beer_id" : "123103","count" : "200","price" : "29.90", "type":"öl"},
        {"namn" : "Oppigårds Amarillo","namn2" : "","sbl_price" : "19.90","pub_price" : "25","beer_id" : "144203","count" : "192","price" : "19.70", "type":"öl"},
        {"namn" : "Oppigårds","namn2" : "Golden Ale","sbl_price" : "17.90","pub_price" : "20","beer_id" : "149003","count" : "202","price" : "17.90", "type":"öl"},
        {"namn" : "Oppigårds","namn2" : "Indian Tribute","sbl_price" : "22.50","pub_price" : "25","beer_id" : "141503","count" : "200","price" : "20.90", "type":"öl"},
        {"namn" : "Oppigårds","namn2" : "Thurbo Double IPA","sbl_price" : "26.30","pub_price" : "30","beer_id" : "8962903","count" : "201","price" : "26.30", "type":"öl"},
        {"namn" : "Paulaner","namn2" : "Hefe-Weissbier","sbl_price" : "20.90","pub_price" : "25","beer_id" : "155701","count" : "200","price" : "20.40", "type":"Öl"},
        {"namn" : "Paulaner Oktoberfest","namn2" : "","sbl_price" : "21.90","pub_price" : "25","beer_id" : "1125001","count" : "200","price" : "21.90", "type":"öl"},
        {"namn" : "Paulaner","namn2" : "Weissbier Kristall","sbl_price" : "20.90","pub_price" : "25","beer_id" : "153001","count" : "198","price" : "19.90", "type":"Öl"},
        {"namn" : "Pilsner Urquell","namn2" : "","sbl_price" : "14.90","pub_price" : "20","beer_id" : "156603","count" : "199","price" : "14.90", "type":"öl"},
        {"namn" : "Pistonhead","namn2" : "Kustom Lager","sbl_price" : "9.90","pub_price" : "15","beer_id" : "145414","count" : "210","price" : "9.90", "type":"öl"},
        {"namn" : "Pistonhead","namn2" : "Plastic Fantastic","sbl_price" : "10.90","pub_price" : "15","beer_id" : "148803","count" : "208","price" : "11.90", "type":"öl"},
        {"namn" : "Poliziano Vino Nobile di Montepulciano","namn2" : "Viti Nuove","sbl_price" : "154.00","pub_price" : "160","beer_id" : "214401","count" : "200","price" : "149.00", "type":"rött_vin"},
        {"namn" : "Primator","namn2" : "Premium Lager","sbl_price" : "10.90","pub_price" : "15","beer_id" : "1151503","count" : "200","price" : "9.90", "type":"öl"},
        {"namn" : "Primátor","namn2" : "Premium Dark","sbl_price" : "14.20","pub_price" : "20","beer_id" : "161503","count" : "200","price" : "13.90", "type":"öl"},
        {"namn" : "Rabarbernektar","namn2" : "","sbl_price" : "39.00","pub_price" : "45","beer_id" : "194203","count" : "183","price" : "39.00", "type":"alcohol-free"},
        {"namn" : "Rochefort 10","namn2" : "","sbl_price" : "39.90","pub_price" : "45","beer_id" : "162703","count" : "200","price" : "39.90", "type":"öl"},
        {"namn" : "Running Duck","namn2" : "Sauvignon Blanc Semillon","sbl_price" : "75.00","pub_price" : "80","beer_id" : "202801","count" : "60","price" : "75.00", "type":"vitt_vin"},
        {"namn" : "Ruppertsberger Hofstück","namn2" : "Riesling","sbl_price" : "65.00","pub_price" : "70","beer_id" : "591401","count" : "198","price" : "65.00", "type":"vitt_vin"},
        {"namn" : "S:t Eriks","namn2" : "Oktoberfest","sbl_price" : "16.90","pub_price" : "20","beer_id" : "1125303","count" : "197","price" : "16.90", "type":"öl"},
        {"namn" : "S:t Eriks","namn2" : "Organic Ale","sbl_price" : "19.90","pub_price" : "25","beer_id" : "1162503","count" : "199","price" : "19.90", "type":"öl"},
        {"namn" : "S:t Eriks Pale Ale","namn2" : "","sbl_price" : "17.90","pub_price" : "20","beer_id" : "142003","count" : "198","price" : "17.90", "type":"öl"},
        {"namn" : "Samuel Adams","namn2" : "Black Lager","sbl_price" : "19.90","pub_price" : "25","beer_id" : "153503","count" : "197","price" : "16.60", "type":"öl"},
        {"namn" : "Samuel Adams","namn2" : "Boston Ale","sbl_price" : "19.90","pub_price" : "25","beer_id" : "164903","count" : "198","price" : "17.90", "type":"öl"},
        {"namn" : "Samuel Adams","namn2" : "Boston Lager","sbl_price" : "17.90","pub_price" : "20","beer_id" : "154603","count" : "195","price" : "15.90", "type":"öl"},
        {"namn" : "Sankt Anna","namn2" : "Riesling","sbl_price" : "49.00","pub_price" : "55","beer_id" : "212002","count" : "200","price" : "49.00", "type":"vitt_vin"},
        {"namn" : "Saxhyttegubbens Blåbär 100%","namn2" : "","sbl_price" : "69.90","pub_price" : "75","beer_id" : "196403","count" : "30","price" : "69.90", "type": "alkohol-free"},
        {"namn" : "Scarecrow","namn2" : "","sbl_price" : "24.90","pub_price" : "30","beer_id" : "1124601","count" : "199","price" : "24.50", "type":"öl"},
        {"namn" : "Shatler's","namn2" : "San Fransisco","sbl_price" : "20.00","pub_price" : "25","beer_id" : "192804","count" : "198","price" : "20.00", "type": "alkohol-free"},
        {"namn" : "Sierra Nevada","namn2" : "Pale Ale","sbl_price" : "23.50","pub_price" : "25","beer_id" : "152503","count" : "199","price" : "23.90", "type":"öl"},
        {"namn" : "Sierra Nevada","namn2" : "Torpedo Extra IPA","sbl_price" : "24.90","pub_price" : "30","beer_id" : "1152803","count" : "200","price" : "26.90", "type":"öl"},
        {"namn" : "Sigtuna East Coast Pale Ale","namn2" : "","sbl_price" : "18.90","pub_price" : "20","beer_id" : "149803","count" : "199","price" : "18.90", "type":"öl"},
        {"namn" : "Sleepy Bulldog","namn2" : "Summer Pale Ale","sbl_price" : "19.80","pub_price" : "25","beer_id" : "8817303","count" : "199","price" : "19.80", "type":"öl"},
        {"namn" : "Slottskällans","namn2" : "Barrel Aged Imperial Stout","sbl_price" : "40.30","pub_price" : "45","beer_id" : "8915103","count" : "199","price" : "39.80", "type":"öl"},
        {"namn" : "Slottskällans Imperial Stout","namn2" : "","sbl_price" : "28.70","pub_price" : "30","beer_id" : "135503","count" : "200","price" : "28.70", "type":"öl"},
        {"namn" : "Slottskällans Princess","namn2" : "","sbl_price" : "19.80","pub_price" : "25","beer_id" : "164103","count" : "200","price" : "24.90", "type":"öl"},
        {"namn" : "Slottskällans Red Ale","namn2" : "","sbl_price" : "20.70","pub_price" : "25","beer_id" : "8875603","count" : "201","price" : "20.70", "type":"öl"},
        {"namn" : "Sofiero Original","namn2" : "","sbl_price" : "9.50","pub_price" : "15","beer_id" : "122203","count" : "200","price" : "9.90", "type":"öl"},
        {"namn" : "Somersby","namn2" : "Apple Cider Organic","sbl_price" : "17.20","pub_price" : "20","beer_id" : "183502","count" : "198","price" : "16.90", "type":"cider"},
        {"namn" : "Somersby","namn2" : "Pear Cider","sbl_price" : "17.20","pub_price" : "20","beer_id" : "182402","count" : "200","price" : "16.90", "type":"cider"},
        {"namn" : "Spaten München","namn2" : "","sbl_price" : "17.90","pub_price" : "20","beer_id" : "1133301","count" : "200","price" : "16.40", "type":"öl"},
        {"namn" : "Spaten Oktoberfestbier","namn2" : "","sbl_price" : "20.60","pub_price" : "25","beer_id" : "1128101","count" : "198","price" : "20.60", "type":"öl"},
        {"namn" : "St Peter's Cream Stout","namn2" : "","sbl_price" : "29.90","pub_price" : "35","beer_id" : "167101","count" : "197","price" : "29.40", "type":"öl"},
        {"namn" : "St Peter's","namn2" : "G-Free Ale","sbl_price" : "36.30","pub_price" : "40","beer_id" : "157701","count" : "200","price" : "36.30", "type":"öl"},
        {"namn" : "Starobrno Premium","namn2" : "","sbl_price" : "13.50","pub_price" : "15","beer_id" : "1134103","count" : "198","price" : "12.90", "type":"öl"},
        {"namn" : "Staropramen","namn2" : "","sbl_price" : "16.40","pub_price" : "20","beer_id" : "167903","count" : "197","price" : "15.90", "type":"öl"},
        {"namn" : "Staropramen Dark","namn2" : "","sbl_price" : "16.40","pub_price" : "20","beer_id" : "163203","count" : "200","price" : "15.90", "type":"öl"},
        {"namn" : "Staropramen Granat","namn2" : "","sbl_price" : "16.40","pub_price" : "20","beer_id" : "160903","count" : "196","price" : "15.90", "type":"öl"},
        {"namn" : "Staropramen","namn2" : "Non-Alcoholic","sbl_price" : "12.40","pub_price" : "15","beer_id" : "193002","count" : "192","price" : "12.40", "type":"alcohol-free"},
        {"namn" : "Störtebeker 1402","namn2" : "","sbl_price" : "11.90","pub_price" : "15","beer_id" : "190002","count" : "200","price" : "10.90", "type":"alcohol-free"},
        {"namn" : "Störtebeker","namn2" : "Bock-Bier","sbl_price" : "16.90","pub_price" : "20","beer_id" : "1159903","count" : "192","price" : "15.90", "type":"öl"},
        {"namn" : "Stella Artois","namn2" : "","sbl_price" : "14.90","pub_price" : "20","beer_id" : "1137903","count" : "188","price" : "14.40", "type":"öl"},
        {"namn" : "Stoneleigh","namn2" : "Riesling","sbl_price" : "99.00","pub_price" : "105","beer_id" : "649801","count" : "195","price" : "104.00", "type":"vitt_vin"},
        {"namn" : "Stowford Press","namn2" : "","sbl_price" : "12.40","pub_price" : "15","beer_id" : "198902","count" : "203","price" : "12.90", "type":"alcohol-free"},
        {"namn" : "Strongbow","namn2" : "","sbl_price" : "15.50","pub_price" : "20","beer_id" : "181902","count" : "188","price" : "15.50", "type":"cider"},
        {"namn" : "Strongbow","namn2" : "","sbl_price" : "18.50","pub_price" : "20","beer_id" : "181903","count" : "198","price" : "17.90", "type":"cider"},
        {"namn" : "Svart","namn2" : "","sbl_price" : "20.70","pub_price" : "25","beer_id" : "1134803","count" : "186","price" : "20.70", "type":"öl"},
        {"namn" : "Thornbridge","namn2" : "Jaipur India Pale Ale","sbl_price" : "27.90","pub_price" : "30","beer_id" : "162601","count" : "191","price" : "27.90", "type":"öl"},
        {"namn" : "Troppo","namn2" : "Merlot Cabernet","sbl_price" : "44.00","pub_price" : "50","beer_id" : "218002","count" : "194","price" : "39.00", "type":"rött_vin"},
        {"namn" : "Via del Campo","namn2" : "Blanco","sbl_price" : "64.00","pub_price" : "70","beer_id" : "645901","count" : "192","price" : "64.00", "type":"vitt_vin"},
        {"namn" : "Viña Maipo","namn2" : "Chardonnay","sbl_price" : "33.00","pub_price" : "35","beer_id" : "667102","count" : "188","price" : "33.00", "type":"vitt_vin"},
        {"namn" : "Weihenstephaner","namn2" : "Hefe Weissbier","sbl_price" : "20.90","pub_price" : "25","beer_id" : "152601","count" : "198","price" : "19.90", "type":"Öl"},
        {"namn" : "Weihenstephaner","namn2" : "Hefeweissbier Alkoholfrei","sbl_price" : "12.90","pub_price" : "15","beer_id" : "192201","count" : "184","price" : "12.90", "type":"alcohol-free"},
        {"namn" : "Wisby","namn2" : "Klosteröl","sbl_price" : "17.80","pub_price" : "20","beer_id" : "140003","count" : "178","price" : "16.90", "type":"öl"},
        {"namn" : "Wyld Wood","namn2" : "Organic","sbl_price" : "27.90","pub_price" : "30","beer_id" : "186602","count" : "194","price" : "27.90", "type":"cider"},
        {"namn" : "Xide Jungle","namn2" : "Passionfruit Habanero","sbl_price" : "15.90","pub_price" : "20","beer_id" : "171903","count" : "191","price" : "15.90", "type": "Blanddrycker"},
        {"namn" : "Xide Non Alco","namn2" : "Lemon Dragonfruit","sbl_price" : "13.90","pub_price" : "15","beer_id" : "192003","count" : "196","price" : "13.90", "type":"alcohol-free"},
        {"namn" : "Xide Pine Citrus","namn2" : "","sbl_price" : "15.90","pub_price" : "20","beer_id" : "178503","count" : "50","price" : "15.90", "type": "Blanddrycker"},
        {"namn" : "Xide Wasabi Lemon","namn2" : "","sbl_price" : "15.90","pub_price" : "20","beer_id" : "182603","count" : "40","price" : "15.90", "type": "Blanddrycker"},
        {"namn" : "Yeti","namn2" : "Imperial Stout","sbl_price" : "33.90","pub_price" : "35","beer_id" : "166703","count" : "643","price" : "31.90", "type":"öl"},
        {"namn" : "Young's Double Chocolate Stout","namn2" : "","sbl_price" : "26.90","pub_price" : "30","beer_id" : "160601","count" : "0","price" : "25.90", "type":"öl"},
        {"namn" : "Zeitgeist","namn2" : "Black Lager","sbl_price" : "18.50","pub_price" : "20","beer_id" : "157803","count" : "20","price" : "15.90", "type":"öl"},
        {"namn" : "Zeunerts","namn2" : "Höga Kusten","sbl_price" : "15.40","pub_price" : "20","beer_id" : "148001","count" : "10","price" : "15.40", "type":"öl"},
        {"namn" : "Zlatopramen","namn2" : " Premium","sbl_price" : "16.90","pub_price" : "20","beer_id" : "158201","count" : "10","price" : "16.90", "type":"öl"}
    ]
}

